from fm_analytics.analytics.role_scoring import (
    AttributeContribution,
    AttributePriority,
    RoleAttribute,
    RoleDefinition,
    RoleScore,
    ScoreBand,
    ScoringPolicy,
    is_position_eligible,
    score_role,
)
from fm_analytics.analytics.role_comparison import (
    CandidateRoleScore,
    RoleComparison,
    ScoutingPriority,
    compare_role_scores,
)
from fm_analytics.analytics.catalogue import (
    MVP_CATALOGUE,
    FootballCatalogue,
    TacticDefinition,
    TacticSlot,
)
from fm_analytics.analytics.xi_selection import (
    PlayerSelectionInput,
    ReadinessPolicy,
    SlotAssignment,
    TacticEvaluation,
    TacticRecommendation,
    evaluate_tactic,
    is_player_selectable,
    recommend_tactic,
    score_player_for_slot,
)
from fm_analytics.analytics.bench_selection import (
    BenchEntry,
    BenchSelection,
    select_bench,
)
from fm_analytics.analytics.weaknesses import (
    DepthCandidate,
    SlotDepth,
    Weakness,
    WeaknessKind,
    WeaknessPolicy,
    WeaknessReport,
    assess_weaknesses,
)
from fm_analytics.analytics.recruitment import (
    CandidateVerdict,
    RecruitmentBrief,
    RecruitmentCandidate,
    RecruitmentShortlist,
    build_recruitment_briefs,
    shortlist_candidates,
)
from fm_analytics.analytics.selection_input import (
    SquadAttributeMerge,
    overlay_squad_export,
)

__all__ = [
    "AttributeContribution",
    "AttributePriority",
    "BenchEntry",
    "BenchSelection",
    "CandidateRoleScore",
    "CandidateVerdict",
    "FootballCatalogue",
    "DepthCandidate",
    "MVP_CATALOGUE",
    "PlayerSelectionInput",
    "ReadinessPolicy",
    "RecruitmentBrief",
    "RecruitmentCandidate",
    "RecruitmentShortlist",
    "RoleAttribute",
    "RoleDefinition",
    "RoleScore",
    "RoleComparison",
    "ScoreBand",
    "ScoringPolicy",
    "ScoutingPriority",
    "SlotAssignment",
    "SlotDepth",
    "SquadAttributeMerge",
    "TacticDefinition",
    "TacticEvaluation",
    "TacticRecommendation",
    "TacticSlot",
    "Weakness",
    "WeaknessKind",
    "WeaknessPolicy",
    "WeaknessReport",
    "assess_weaknesses",
    "build_recruitment_briefs",
    "compare_role_scores",
    "evaluate_tactic",
    "is_position_eligible",
    "is_player_selectable",
    "overlay_squad_export",
    "recommend_tactic",
    "score_player_for_slot",
    "select_bench",
    "shortlist_candidates",
    "score_role",
]
